# 1.1 


In [2]:
import numpy as np

# Создать вектор как строку
vector_row = np.array([1, 2, 3])
# Создать вектор как столбец
vector_column = np.array([[1],
                          [2],
                          [3]])

# Создать матрицу
matrix = np.array([[1, 2],
                   [1, 2],
                   [1, 2]])

matrix_object = np.mat([[1, 2],
                        [1, 2],
                        [1, 2]])

# 1.2

In [6]:
# Загрузить библиотеку
from scipy import sparse

# Создать матрицу
matrix2 = np.array([[0, 0],
                    [0, 1],
                    [3, 0]])

# Создать разреженную матрицу - строку (CSR - матрицу)
matrix_sparse = sparse.csr_matrix(matrix2)




# Создать более крупную разреженную матрицу - строку, но сначала создадим обычную матрицу

matrix_larger = ([[0, 0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 1, 0, 0, 0, 0, 0, 0, 0],
                  [3, 0, 0, 0, 0, 0, 0, 0, 0]])

matrix_larger_sparse = sparse.csr_matrix(matrix_larger)

# Взглянуть на исходную разреженную матрицу
print(matrix_sparse)

# Взглянуть на более крупную разреженную матрицу
print(matrix_larger_sparse)

  (1, 1)	1
  (2, 0)	3
  (1, 1)	1
  (2, 0)	3


# 1.4 Выбор элементов


In [7]:
import numpy as np

# Создать вектор - строку
vector = np.array([1, 2, 3, 4, 5, 6])

# Создать матрицу
matrix4 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

# Выбрать 3 элемент в векторе
print(vector[2])

# Выбрать вторую строку второй элемент в матрице
print(matrix4[1, 1])

3
5


# 1.5 Описание матрицы


In [8]:
import numpy as np

# Создать матрицу
matrix5 = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

# Взглянуть на кол - во строк и столбцов
print(matrix5.shape)

# Взглянуть на кол - во элементов (строки * столбцы)
print(matrix5.size)

# Взглянуть на кол - во размерностей
print(matrix5.ndim)

(3, 4)
12
2


# 1.6 Применение операций к елементам


In [9]:
import numpy as np

matrix6 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

# Make function that add 100 to matrix6
add_100 = lambda i: i + 100

# Make vectorized function
vectorized_add_100 = np.vectorize(add_100)

# Add this func to all elements of the matrix
vectorized_add_100(matrix6)
print(vectorized_add_100(matrix6))

[[101 102 103]
 [104 105 106]
 [107 108 109]]


# 1.7 Find max or min in array


In [10]:
import numpy as np

matrix7 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

print(np.max(matrix7))
print(np.min(matrix7))

# Find max element in every column (Столбец)
print(np.max(matrix7, axis=0))

# Find max element in every line (Строка)
print(np.max(matrix7, axis=1))


9
1
[7 8 9]
[3 6 9]


# 1.8 Вычисление среднего значения, дисперсии и стандартного отклонения


In [11]:
import numpy as np

matrix8 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

# Вывести среднее значение
print('Среднее значение: ', np.mean(matrix8))

# Вернуть дисперсию
print('Дисперсия: ', np.var(matrix8))

# Вернуть стандартное отклонение
print('Среднее отклонение: ', np.std(matrix8))

# Найти среднее значение в каждом отдельном столбце
print('Среднее значение в каждом отдельном столбце: ', np.mean(matrix8, axis=0))

Среднее значение:  5.0
Дисперсия:  6.666666666666667
Среднее отклонение:  2.581988897471611
Среднее значение в каждом отдельном столбце:  [4. 5. 6.]


# 1.9 Реформирование массивов


In [14]:
import numpy as np

matrix9 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9],
                    [10, 11, 12]])

print('Исходная матрица: ', matrix9)

# Реформировать таблицу в матрицу 2 * 6
print('Реформированная матрица: ', matrix9.reshape(2, 6))

# Увидеть размер матрицы
print('Размер таблицы: ', matrix9.size)

# Увидеть одну строку и столько столбцов, сколько необходимо
print('Строки и столбцы по необходимости: ', matrix9.reshape(1, -1))

# Увидеть одномерный массив этой длины
print('Одномерный массив нужной длины: ', matrix9.reshape(12))

Исходная матрица:  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Реформированная матрица:  [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Размер таблицы:  12
Строки и столбцы по необходимости:  [[ 1  2  3  4  5  6  7  8  9 10 11 12]]
Одномерный массив нужной длины:  [ 1  2  3  4  5  6  7  8  9 10 11 12]


# 1.10 Транспортирование вектора в матрицу




In [20]:
import numpy as np

matrix10 = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Транспонировать матрицу
print('Транспонированная матрица:', matrix10.T)

Транспонированная матрица: [[1 4 7]
 [2 5 8]
 [3 6 9]]


# 1.11 Сглаживание матрицы


In [21]:
import numpy as np

matrix11 = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Сгладить матрицу (привести к одномерному массиву)
print('Сглаженная матрица (Одномерный массив): ', matrix11.flatten())

Сглаженная матрица (Одномерный массив):  [1 2 3 4 5 6 7 8 9]


# 1.12 Нахождение ранга матрицы


In [23]:
import numpy as np

matrix12 = np.array([[1, 1, 1],
                     [1, 1, 10],
                     [1, 1, 15]])

# Вернуть ранг матрицы
print('Ранг матрицы: ', np.linalg.matrix_rank(matrix12))

Ранг матрицы:  2


# 1.13 Вычисление определителя матрицы


In [24]:
import numpy as np

matrix13 = np.array([[1, 2, 3],
                     [2, 4, 6],
                     [3, 8, 9]])

# Вернуть определитель матрицы
print('Определитель матрицы: ', np.linalg.det(matrix13))

Определитель матрицы:  6.661338147750893e-16


# 1.14 Получение диагонали матрицы


In [25]:
import numpy as np

matrix14 = np.array([[1, 2, 3],
                     [2, 4, 6],
                     [3, 8, 9]])

# Вернуть диагональные элементы
print('Диагональные элементы матрицы: ', matrix14.diagonal())

# Вернуть диагональ на одну выше главной диагонали
print('Диагональ на одну выше главной:', matrix14.diagonal(offset=1))

# Вернуть диагональ на одну ниже главной диагонали
print('Диагональ на одну ниже главной:', matrix14.diagonal(offset=-1))

Диагональные элементы матрицы:  [1 4 9]
Диагональ на одну выше главной: [2 6]
Диагональ на одну ниже главной: [2 8]


# 1.15 Вычисление следа матрицы


In [27]:
import numpy as np

matrix15 = np.array([[1, 2, 3],
                     [2, 4, 6],
                     [3, 8, 9]])

# Вернуть след
print('След матрицы: ', matrix15.trace())

# Альтернативный способ вычисления следа матрицы вернув сумму её эл-ов
print('След матрциы через сумму эл-ов главной диаг-ли: ',sum(matrix15.diagonal()))

След матрицы:  14
След матрциы через сумму эл-ов главной диаг-ли:  14


# 1.16 Нахождение собственных значений и собственных векторов


In [29]:
import numpy as np

matrix16 = np.array([[1, -1, 3],
                     [1, 1, 6],
                     [3, 8, 9]])

# Вычислить собственные значения и векторы
eigenvalues, eigenvectors = np.linalg.eig(matrix16)

print('Собственные значения: ', eigenvalues)
print('Собственные векторы: ', eigenvectors)

Собственные значения:  [13.55075847  0.74003145 -3.29078992]
Собственные векторы:  [[-0.17622017 -0.96677403 -0.53373322]
 [-0.435951    0.2053623  -0.64324848]
 [-0.88254925  0.15223105  0.54896288]]


# 1.17 Вычисление скалярных произведений


In [31]:
import numpy as np

vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

# Вычислить скалярное произведение
print('Скалярное произведение векторов: ', np.dot(vector_a,vector_b))

# Альтернативный способ нахождения скалярного произведения
print('Альтернативный способ через @:', vector_a @ vector_b)

Скалярное произведение векторов:  32
Альтернативный способ через @: 32


# 1.18 Сложение и вычитание матриц


In [33]:
import numpy as np

matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

# Сложить матрицы
print('Сложение матриц: ', np.add(matrix_b, matrix_a))

#print(matrix_b + matrix_a)

# Вычесть из одной матрицу другую
print('Вычитание двух матриц: ', matrix_a - matrix_b)

#print(np.subtract(matrix_a, matrix_b))

# Умножить одну матрицу на другую
print('Умножение двух матриц:', matrix_a * matrix_b)

Сложение матриц:  [[ 2  4  2]
 [ 2  4  2]
 [ 2  4 10]]
Вычитание двух матриц:  [[ 0 -2  0]
 [ 0 -2  0]
 [ 0 -2 -6]]
Умножение двух матриц: [[ 1  3  1]
 [ 1  3  1]
 [ 1  3 16]]


# 1.20 Обращение матрицы


In [34]:
import numpy as np

matrix20 = np.array([[1, 4],
                     [2, 5]])

# Вычислить обратную матрицу
print('Обратная матрица: ', np.linalg.inv(matrix20))

Обратная матрица:  [[-1.66666667  1.33333333]
 [ 0.66666667 -0.33333333]]


# 1.21 Генерирование случайных значений


In [42]:
import numpy as np

# Задать начальное значение для генератора псевдослучайных чисел
np.random.seed(0)

In [37]:
# Сгенерировать три случайных ВЕЩЕСТВЕННЫХ числа между 0 и 1
print('Три случайных ВЕЩЕСТВЕННЫХ числа между 0 и 1: ', np.random.random(3))

Три случайных ВЕЩЕСТВЕННЫХ числа между 0 и 1:  [0.33739616 0.64817187 0.36824154]


In [38]:
# Сгенерировать три случайных ЦЕЛЫХ числа между 1 и 10
print('Три случайных ЦЕЛЫХ числа между 1 и 10: ', np.random.randint(0, 11, 3))

Три случайных ЦЕЛЫХ числа между 1 и 10:  [5 0 2]


In [39]:
# Извлечь три числа из нормального распределения со средним равным 0 и стандартным отклонением равным 1
print('Три числа из нормального распределения со средним равным 0 и стандартным отклонением равным 1: ', np.random.normal(0.0, 1.0, 3))

Три числа из нормального распределения со средним равным 0 и стандартным отклонением равным 1:  [-0.13309028  1.41437719 -0.12405066]


In [40]:
# Извлечь три числа из логистического распределения со средним равным 0 и масштабом равным 1
print('Три числа из логистического распределения со средним равным 0 и масштабом равным 1: ', np.random.logistic(0, 1, 3))

Три числа из логистического распределения со средним равным 0 и масштабом равным 1:  [0.08195576 0.74862734 0.94760195]


In [41]:
# Извлечь три числа, которые больше или равны 1 и меньше 2
print('Три числа, которые больше или равны 1 и меньше 2: ', np.random.uniform(1, 2, 3))

Три числа, которые больше или равны 1 и меньше 2:  [1.58201979 1.53737323 1.75861562]
